_ = com_geek_afric_client_AppManager$13.prototype;
_.onSuccess__V = function com_geek_afric_client_AppManager$13_onSuccess__V(){
  var passUpdate;
  passUpdate = new com_geek_afric_client_view_PasswordUpdate_PasswordUpdate__Ljava_lang_String_2Lcom_geek_afric_client_GeekServiceAsync_2Lcom_google_gwt_event_shared_HandlerManager_2V(this.com_geek_afric_client_AppManager$13_this$0.com_geek_afric_client_AppManager_part2, this.com_geek_afric_client_AppManager$13_this$0.com_geek_afric_client_AppManager_rpcService, this.com_geek_afric_client_AppManager$13_this$0.com_geek_afric_client_AppManager_eventBus);
  com_geek_afric_client_view_PasswordUpdate_$go__Lcom_geek_afric_client_view_PasswordUpdate_2Lcom_google_gwt_user_client_ui_HasWidgets_2V(passUpdate, this.com_geek_afric_client_AppManager$13_this$0.com_geek_afric_client_AppManager_container);
}
;
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(7);
