var $intern_210 = 'Mails (', $intern_212 = 'home-panel', $intern_207 = 'label-title-acceuil';
function com_geek_afric_client_AppManager_$doShowMails__Lcom_geek_afric_client_AppManager_2Ljava_lang_String_2IV(box, startIndex){
  com_google_gwt_user_client_History_$clinit__V();
  !!com_google_gwt_user_client_History_impl && com_google_gwt_user_client_impl_HistoryImpl_$newItem__Lcom_google_gwt_user_client_impl_HistoryImpl_2Ljava_lang_String_2ZV(com_google_gwt_user_client_History_impl, 'mails=box?' + box + $intern_197 + startIndex);
}

_ = com_geek_afric_client_AppManager$8.prototype;
_.onSuccess__V = function com_geek_afric_client_AppManager$8_onSuccess__V(){
  var acceuil, presenter;
  acceuil = new com_geek_afric_client_view_Acceuil_Acceuil__Lcom_geek_afric_shared_User_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_user);
  presenter = new com_geek_afric_client_presenter_AcceuilPresenter_AcceuilPresenter__Lcom_geek_afric_client_GeekServiceAsync_2Lcom_google_gwt_event_shared_HandlerManager_2Lcom_geek_afric_client_presenter_AcceuilPresenter$Display_2Lcom_geek_afric_shared_User_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_rpcService, this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_eventBus, acceuil, this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_user);
  com_geek_afric_client_presenter_AcceuilPresenter_$go__Lcom_geek_afric_client_presenter_AcceuilPresenter_2Lcom_google_gwt_user_client_ui_HasWidgets_2V(presenter, this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_container);
  com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_topContainer);
  com_google_gwt_user_client_ui_AbsolutePanel_$add__Lcom_google_gwt_user_client_ui_AbsolutePanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_topContainer, acceuil.com_geek_afric_client_view_Acceuil_topPanel);
  com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_leftContainer);
  com_google_gwt_user_client_ui_AbsolutePanel_$add__Lcom_google_gwt_user_client_ui_AbsolutePanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_AppManager$8_this$0.com_geek_afric_client_AppManager_leftContainer, acceuil.com_geek_afric_client_view_Acceuil_leftPanel);
}
;
function com_geek_afric_client_GeekService_1Proxy_$getUnreadCount__Lcom_geek_afric_client_GeekService_1Proxy_2Lcom_geek_afric_shared_User_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2V(this$static, user, callback){
  var $e0, helper, streamWriter;
  helper = new com_google_gwt_user_client_rpc_impl_RemoteServiceProxy$ServiceHelper_RemoteServiceProxy$ServiceHelper__Lcom_google_gwt_user_client_rpc_impl_RemoteServiceProxy_2Ljava_lang_String_2Ljava_lang_String_2V(this$static, 'getUnreadCount');
  try {
    streamWriter = com_google_gwt_user_client_rpc_impl_RemoteServiceProxy$ServiceHelper_$start__Lcom_google_gwt_user_client_rpc_impl_RemoteServiceProxy$ServiceHelper_2Ljava_lang_String_2ILcom_google_gwt_user_client_rpc_SerializationStreamWriter_2(helper, 1);
    com_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_$writeInt__Lcom_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_2IV(streamWriter, com_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_$addString__Lcom_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_2Ljava_lang_String_2I(streamWriter, $intern_23));
    com_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_$writeObject__Lcom_google_gwt_user_client_rpc_impl_AbstractSerializationStreamWriter_2Ljava_lang_Object_2V(streamWriter, user);
    com_google_gwt_user_client_rpc_impl_RemoteServiceProxy$ServiceHelper_$finish__Lcom_google_gwt_user_client_rpc_impl_RemoteServiceProxy$ServiceHelper_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2Lcom_google_gwt_user_client_rpc_impl_RequestCallbackAdapter$ResponseReader_2Lcom_google_gwt_http_client_Request_2(helper, callback, (com_google_gwt_user_client_rpc_impl_RequestCallbackAdapter$ResponseReader_$clinit__V() , com_google_gwt_user_client_rpc_impl_RequestCallbackAdapter$ResponseReader_INT));
  }
   catch ($e0) {
    $e0 = com_google_gwt_lang_Exceptions_caught__Ljava_lang_Object_2Ljava_lang_Object_2($e0);
    if (com_google_gwt_lang_Cast_instanceOf__Ljava_lang_Object_2IZ($e0, Q$com_google_gwt_user_client_rpc_SerializationException)) {
      com_geek_afric_client_view_Acceuil_$setMailCount__Lcom_geek_afric_client_view_Acceuil_2IV(callback.com_geek_afric_client_presenter_AcceuilPresenter$4_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, 0);
    }
     else 
      throw $e0;
  }
}

function com_geek_afric_client_event_MailEvent_$dispatch__Lcom_geek_afric_client_event_MailEvent_2Lcom_geek_afric_client_event_MailEventHandler_2V(this$static){
  com_geek_afric_client_AppManager_$doShowMails__Lcom_geek_afric_client_AppManager_2Ljava_lang_String_2IV(this$static.com_geek_afric_client_event_MailEvent_box, this$static.com_geek_afric_client_event_MailEvent_startIndex);
}

function com_geek_afric_client_event_MailEvent_MailEvent__Lcom_geek_afric_shared_User_2ILjava_lang_String_2V(){
  com_geek_afric_client_event_MailEvent_$clinit__V();
  this.com_geek_afric_client_event_MailEvent_startIndex = 0;
  this.com_geek_afric_client_event_MailEvent_box = $intern_198;
}

function com_geek_afric_client_event_MailEvent(){
}

_ = com_geek_afric_client_event_MailEvent_MailEvent__Lcom_geek_afric_shared_User_2ILjava_lang_String_2V.prototype = com_geek_afric_client_event_MailEvent.prototype = new com_google_gwt_event_shared_GwtEvent;
_.dispatch__Lcom_google_gwt_event_shared_EventHandler_2V = function com_geek_afric_client_event_MailEvent_dispatch__Lcom_google_gwt_event_shared_EventHandler_2V(handler){
  com_geek_afric_client_event_MailEvent_$dispatch__Lcom_geek_afric_client_event_MailEvent_2Lcom_geek_afric_client_event_MailEventHandler_2V(this, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(handler, Q$com_geek_afric_client_event_MailEventHandler));
}
;
_.getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2 = function com_geek_afric_client_event_MailEvent_getAssociatedType__Lcom_google_gwt_event_shared_GwtEvent$Type_2(){
  return com_geek_afric_client_event_MailEvent_TYPE;
}
;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_event_MailEvent_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1event_1MailEvent_12_1classLit;
}
;
_.com_geek_afric_client_event_MailEvent_box = null;
_.com_geek_afric_client_event_MailEvent_startIndex = 0;
function com_geek_afric_client_presenter_AcceuilPresenter_$go__Lcom_geek_afric_client_presenter_AcceuilPresenter_2Lcom_google_gwt_user_client_ui_HasWidgets_2V(this$static, container){
  com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(container);
  com_google_gwt_user_client_ui_AbsolutePanel_$add__Lcom_google_gwt_user_client_ui_AbsolutePanel_2Lcom_google_gwt_user_client_ui_Widget_2V(container, this$static.com_geek_afric_client_presenter_AcceuilPresenter_display);
  com_geek_afric_client_GeekService_1Proxy_$getSearchTokens__Lcom_geek_afric_client_GeekService_1Proxy_2Lcom_geek_afric_shared_User_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter_rpcService, this$static.com_geek_afric_client_presenter_AcceuilPresenter_user, new com_geek_afric_client_presenter_AcceuilPresenter$2_AcceuilPresenter$2__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$static));
  com_geek_afric_client_view_Acceuil_$setLoader__Lcom_geek_afric_client_view_Acceuil_2ZV(this$static.com_geek_afric_client_presenter_AcceuilPresenter_display, true);
  com_geek_afric_client_GeekService_1Proxy_$getFilesByUserId__Lcom_geek_afric_client_GeekService_1Proxy_2Ljava_lang_String_2ILjava_lang_String_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter_rpcService, this$static.com_geek_afric_client_presenter_AcceuilPresenter_user.com_geek_afric_shared_ObjetStandard_id, $intern_199, new com_geek_afric_client_presenter_AcceuilPresenter$3_AcceuilPresenter$3__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$static));
  com_geek_afric_client_GeekService_1Proxy_$getUnreadCount__Lcom_geek_afric_client_GeekService_1Proxy_2Lcom_geek_afric_shared_User_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter_rpcService, this$static.com_geek_afric_client_presenter_AcceuilPresenter_user, new com_geek_afric_client_presenter_AcceuilPresenter$4_AcceuilPresenter$4__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$static));
}

function com_geek_afric_client_presenter_AcceuilPresenter_AcceuilPresenter__Lcom_geek_afric_client_GeekServiceAsync_2Lcom_google_gwt_event_shared_HandlerManager_2Lcom_geek_afric_client_presenter_AcceuilPresenter$Display_2Lcom_geek_afric_shared_User_2V(rpcService, eventBus, display, user){
  this.com_geek_afric_client_presenter_AcceuilPresenter_rpcService = rpcService;
  this.com_geek_afric_client_presenter_AcceuilPresenter_eventBus = eventBus;
  this.com_geek_afric_client_presenter_AcceuilPresenter_display = display;
  this.com_geek_afric_client_presenter_AcceuilPresenter_user = user;
  com_geek_afric_client_view_Acceuil_$setListener__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_client_view_Acceuil$Listener_2V(this.com_geek_afric_client_presenter_AcceuilPresenter_display, new com_geek_afric_client_presenter_AcceuilPresenter$1_AcceuilPresenter$1__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this));
}

function com_geek_afric_client_presenter_AcceuilPresenter(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter_AcceuilPresenter__Lcom_geek_afric_client_GeekServiceAsync_2Lcom_google_gwt_event_shared_HandlerManager_2Lcom_geek_afric_client_presenter_AcceuilPresenter$Display_2Lcom_geek_afric_shared_User_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter_12_1classLit;
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter_display = null;
_.com_geek_afric_client_presenter_AcceuilPresenter_eventBus = null;
_.com_geek_afric_client_presenter_AcceuilPresenter_rpcService = null;
_.com_geek_afric_client_presenter_AcceuilPresenter_user = null;
function com_geek_afric_client_presenter_AcceuilPresenter$1_$getRechercheSelectHandler__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Lcom_google_gwt_event_logical_shared_SelectionHandler_2(this$static){
  var selection;
  selection = new com_geek_afric_client_presenter_AcceuilPresenter$1$2_AcceuilPresenter$1$2__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$static);
  return selection;
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickDeconnexion__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$static){
  com_geek_afric_client_GeekService_1Proxy_$logout__Lcom_geek_afric_client_GeekService_1Proxy_2Lcom_geek_afric_shared_User_2Lcom_google_gwt_user_client_rpc_AsyncCallback_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_rpcService, this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_user, new com_geek_afric_client_presenter_AcceuilPresenter$1$1_AcceuilPresenter$1$1__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$static));
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickFichiers__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$static){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_user.com_geek_afric_shared_ObjetStandard_id, 0));
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickSearch__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Ljava_lang_String_2V(this$static, token){
  token != null && !!token.length && com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV(token, 0));
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickShowFiles__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Ljava_lang_String_2V(this$static){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_user.com_geek_afric_shared_ObjetStandard_id, 0));
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickTitle__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Lcom_geek_afric_shared_Fichier_2V(this$static, file){
  !file?com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierEvent_FichierEvent__Ljava_lang_String_2V(null)):com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierEvent_FichierEvent__Ljava_lang_String_2V(file.com_geek_afric_shared_ObjetStandard_id));
}

function com_geek_afric_client_presenter_AcceuilPresenter$1_AcceuilPresenter$1__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$0){
  this.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0 = this$0;
}

function com_geek_afric_client_presenter_AcceuilPresenter$1(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$1_AcceuilPresenter$1__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$1.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1_12_1classLit;
}
;
_.getRechercheSelectHandler__Lcom_google_gwt_event_logical_shared_SelectionHandler_2 = function com_geek_afric_client_presenter_AcceuilPresenter$1_getRechercheSelectHandler__Lcom_google_gwt_event_logical_shared_SelectionHandler_2(){
  return new com_geek_afric_client_presenter_AcceuilPresenter$1$2_AcceuilPresenter$1$2__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this);
}
;
_.onClickAcceuil__V = function com_geek_afric_client_presenter_AcceuilPresenter$1_onClickAcceuil__V(){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_AcceuilEvent_AcceuilEvent__V);
}
;
_.onClickDeconnexion__V = function com_geek_afric_client_presenter_AcceuilPresenter$1_onClickDeconnexion__V(){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickDeconnexion__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this);
}
;
_.onClickFichiers__V = function com_geek_afric_client_presenter_AcceuilPresenter$1_onClickFichiers__V(){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickFichiers__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this);
}
;
_.onClickPartages__V = function com_geek_afric_client_presenter_AcceuilPresenter$1_onClickPartages__V(){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV($intern_200, 0));
}
;
_.onClickSearch__Ljava_lang_String_2V = function com_geek_afric_client_presenter_AcceuilPresenter$1_onClickSearch__Ljava_lang_String_2V(token){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickSearch__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Ljava_lang_String_2V(this, token);
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0 = null;
function com_geek_afric_client_presenter_AcceuilPresenter$1$1_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$1$1_2Ljava_lang_Void_2V(this$static){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$1$1_this$1.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_UserLogoutEvent_UserLogoutEvent__Lcom_geek_afric_shared_User_2V);
  com_google_gwt_user_client_Window_setTitle__Ljava_lang_String_2V($intern_201);
}

function com_geek_afric_client_presenter_AcceuilPresenter$1$1_AcceuilPresenter$1$1__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$1){
  this.com_geek_afric_client_presenter_AcceuilPresenter$1$1_this$1 = this$1;
}

function com_geek_afric_client_presenter_AcceuilPresenter$1$1(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$1$1_AcceuilPresenter$1$1__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$1$1.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$1$1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1$1_12_1classLit;
}
;
_.onFailure__Ljava_lang_Throwable_2V = function com_geek_afric_client_presenter_AcceuilPresenter$1$1_onFailure__Ljava_lang_Throwable_2V(caught){
  com_google_gwt_user_client_Window_alert__Ljava_lang_String_2V($intern_202 + caught.getMessage__Ljava_lang_String_2());
}
;
_.onSuccess__Ljava_lang_Object_2V = function com_geek_afric_client_presenter_AcceuilPresenter$1$1_onSuccess__Ljava_lang_Object_2V(result){
  com_geek_afric_client_presenter_AcceuilPresenter$1$1_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$1$1_2Ljava_lang_Void_2V(this, com_google_gwt_lang_Cast_throwClassCastExceptionUnlessNull__Ljava_lang_Object_2Ljava_lang_Object_2(result));
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter$1$1_this$1 = null;
function com_geek_afric_client_presenter_AcceuilPresenter$1$2_AcceuilPresenter$1$2__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this$1){
  this.com_geek_afric_client_presenter_AcceuilPresenter$1$2_this$1 = this$1;
}

function com_geek_afric_client_presenter_AcceuilPresenter$1$2(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$1$2_AcceuilPresenter$1$2__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$1$2.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$1$2_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1$2_12_1classLit;
}
;
_.onSelection__Lcom_google_gwt_event_logical_shared_SelectionEvent_2V = function com_geek_afric_client_presenter_AcceuilPresenter$1$2_onSelection__Lcom_google_gwt_event_logical_shared_SelectionEvent_2V(event){
  var token;
  token = com_geek_afric_client_view_Acceuil_$getSelectToken__Lcom_geek_afric_client_view_Acceuil_2Ljava_lang_String_2(this.com_geek_afric_client_presenter_AcceuilPresenter$1$2_this$1.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display);
  token != null && !!token.length && com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_presenter_AcceuilPresenter$1$2_this$1.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV(token, 0));
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_logical_shared_SelectionHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.com_geek_afric_client_presenter_AcceuilPresenter$1$2_this$1 = null;
function com_geek_afric_client_presenter_AcceuilPresenter$2_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$2_2Ljava_util_Set_2V(this$static, result){
  com_geek_afric_client_view_Acceuil_$setTokens__Lcom_geek_afric_client_view_Acceuil_2Ljava_util_Set_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$2_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, result);
}

function com_geek_afric_client_presenter_AcceuilPresenter$2_AcceuilPresenter$2__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$0){
  this.com_geek_afric_client_presenter_AcceuilPresenter$2_this$0 = this$0;
}

function com_geek_afric_client_presenter_AcceuilPresenter$2(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$2_AcceuilPresenter$2__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$2.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$2_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$2_12_1classLit;
}
;
_.onFailure__Ljava_lang_Throwable_2V = function com_geek_afric_client_presenter_AcceuilPresenter$2_onFailure__Ljava_lang_Throwable_2V(caught){
  com_google_gwt_user_client_Window_alert__Ljava_lang_String_2V($intern_203 + caught.getMessage__Ljava_lang_String_2());
}
;
_.onSuccess__Ljava_lang_Object_2V = function com_geek_afric_client_presenter_AcceuilPresenter$2_onSuccess__Ljava_lang_Object_2V(result){
  com_geek_afric_client_presenter_AcceuilPresenter$2_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$2_2Ljava_util_Set_2V(this, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(result, Q$java_util_Set));
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter$2_this$0 = null;
function com_geek_afric_client_presenter_AcceuilPresenter$3_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$3_2Ljava_util_ArrayList_2V(this$static, result){
  com_geek_afric_client_view_Acceuil_$setFichiers__Lcom_geek_afric_client_view_Acceuil_2Ljava_util_ArrayList_2V(this$static.com_geek_afric_client_presenter_AcceuilPresenter$3_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, result);
  com_geek_afric_client_view_Acceuil_$setLoader__Lcom_geek_afric_client_view_Acceuil_2ZV(this$static.com_geek_afric_client_presenter_AcceuilPresenter$3_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, false);
  com_google_gwt_user_client_Window_setTitle__Ljava_lang_String_2V($intern_201);
}

function com_geek_afric_client_presenter_AcceuilPresenter$3_AcceuilPresenter$3__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$0){
  this.com_geek_afric_client_presenter_AcceuilPresenter$3_this$0 = this$0;
}

function com_geek_afric_client_presenter_AcceuilPresenter$3(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$3_AcceuilPresenter$3__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$3.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$3_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$3_12_1classLit;
}
;
_.onFailure__Ljava_lang_Throwable_2V = function com_geek_afric_client_presenter_AcceuilPresenter$3_onFailure__Ljava_lang_Throwable_2V(caught){
  com_google_gwt_user_client_Window_alert__Ljava_lang_String_2V($intern_204 + caught.getMessage__Ljava_lang_String_2());
  com_geek_afric_client_view_Acceuil_$setLoader__Lcom_geek_afric_client_view_Acceuil_2ZV(this.com_geek_afric_client_presenter_AcceuilPresenter$3_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, false);
}
;
_.onSuccess__Ljava_lang_Object_2V = function com_geek_afric_client_presenter_AcceuilPresenter$3_onSuccess__Ljava_lang_Object_2V(result){
  com_geek_afric_client_presenter_AcceuilPresenter$3_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$3_2Ljava_util_ArrayList_2V(this, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(result, Q$java_util_ArrayList));
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter$3_this$0 = null;
function com_geek_afric_client_presenter_AcceuilPresenter$4_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$4_2Ljava_lang_Integer_2V(this$static, result){
  com_geek_afric_client_view_Acceuil_$setMailCount__Lcom_geek_afric_client_view_Acceuil_2IV(this$static.com_geek_afric_client_presenter_AcceuilPresenter$4_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, result.java_lang_Integer_value);
}

function com_geek_afric_client_presenter_AcceuilPresenter$4_AcceuilPresenter$4__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V(this$0){
  this.com_geek_afric_client_presenter_AcceuilPresenter$4_this$0 = this$0;
}

function com_geek_afric_client_presenter_AcceuilPresenter$4(){
}

_ = com_geek_afric_client_presenter_AcceuilPresenter$4_AcceuilPresenter$4__Lcom_geek_afric_client_presenter_AcceuilPresenter_2V.prototype = com_geek_afric_client_presenter_AcceuilPresenter$4.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_presenter_AcceuilPresenter$4_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$4_12_1classLit;
}
;
_.onFailure__Ljava_lang_Throwable_2V = function com_geek_afric_client_presenter_AcceuilPresenter$4_onFailure__Ljava_lang_Throwable_2V(caught){
  com_geek_afric_client_view_Acceuil_$setMailCount__Lcom_geek_afric_client_view_Acceuil_2IV(this.com_geek_afric_client_presenter_AcceuilPresenter$4_this$0.com_geek_afric_client_presenter_AcceuilPresenter_display, 0);
}
;
_.onSuccess__Ljava_lang_Object_2V = function com_geek_afric_client_presenter_AcceuilPresenter$4_onSuccess__Ljava_lang_Object_2V(result){
  com_geek_afric_client_presenter_AcceuilPresenter$4_$onSuccess__Lcom_geek_afric_client_presenter_AcceuilPresenter$4_2Ljava_lang_Integer_2V(this, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2(result, Q$java_lang_Integer));
}
;
_.com_geek_afric_client_presenter_AcceuilPresenter$4_this$0 = null;
function com_geek_afric_client_view_Acceuil_$createEmptyFile__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2(this$static){
  var panel, welcome;
  panel = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  welcome = new com_google_gwt_user_client_ui_Label_Label__V;
  com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(welcome.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, $intern_205, false);
  welcome.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = $intern_207;
  welcome.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(panel, welcome);
  com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(welcome, new com_geek_afric_client_view_Acceuil$5_Acceuil$5__Lcom_geek_afric_client_view_Acceuil_2V(this$static), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE));
  panel.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185;
  panel.com_google_gwt_user_client_ui_UIObject_element.style[$intern_180] = $intern_185;
  return panel;
}

function com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, file){
  var content, date, html, panel, text, title;
  panel = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  title = new com_google_gwt_user_client_ui_Label_Label__V;
  com_google_gwt_user_client_ui_Label_$setText__Lcom_google_gwt_user_client_ui_Label_2Ljava_lang_String_2V(title, file.com_geek_afric_shared_AbstractFichier_title);
  title.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = $intern_207;
  title.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185;
  com_google_gwt_user_client_ui_UIObject_$setTitle__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2V(title, 'Aller au fichier ' + file.com_geek_afric_shared_AbstractFichier_title);
  com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(title, new com_geek_afric_client_view_Acceuil$3_Acceuil$3__Lcom_geek_afric_client_view_Acceuil_2V(this$static, file), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE));
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(panel, title);
  com_google_gwt_user_client_ui_CellPanel_$setCellVerticalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasVerticalAlignment$VerticalAlignmentConstant_2V(panel, title, (com_google_gwt_user_client_ui_HasVerticalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasVerticalAlignment_ALIGN_1TOP));
  html = new com_google_gwt_user_client_ui_HTML_HTML__V;
  content = new com_google_gwt_user_client_ui_HTML_HTML__Ljava_lang_String_2V(file.com_geek_afric_shared_Fichier_contenu);
  text = com_google_gwt_user_client_ui_DirectionalTextHelper_$getTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2ZLjava_lang_String_2(content.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, false);
  com_google_gwt_user_client_ui_HTML_$setHTML__Lcom_google_gwt_user_client_ui_HTML_2Ljava_lang_String_2V(html, text.length < 100?text:text.substr(0, 100 - 0) + $intern_90);
  html.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185;
  html.com_google_gwt_user_client_ui_UIObject_element.style[$intern_180] = $intern_185;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(panel, html);
  date = new com_google_gwt_user_client_ui_Label_Label__V;
  com_google_gwt_user_client_ui_Label_$setText__Lcom_google_gwt_user_client_ui_Label_2Ljava_lang_String_2V(date, file.com_geek_afric_shared_ObjetStandard_dateDerniereModif.java_util_Date_jsdate.toLocaleString());
  date.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = $intern_208;
  com_google_gwt_user_client_ui_CellPanel_$setCellHorizontalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(panel, date, (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT));
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(panel, date);
  com_google_gwt_user_client_ui_CellPanel_$setCellVerticalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasVerticalAlignment$VerticalAlignmentConstant_2V(panel, date, com_google_gwt_user_client_ui_HasVerticalAlignment_ALIGN_1BOTTOM);
  panel.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185;
  panel.com_google_gwt_user_client_ui_UIObject_element.style[$intern_180] = $intern_185;
  return panel;
}

function com_geek_afric_client_view_Acceuil_$getSelectToken__Lcom_geek_afric_client_view_Acceuil_2Ljava_lang_String_2(this$static){
  var token;
  token = null;
  !!this$static.com_geek_afric_client_view_Acceuil_topPanel && (token = com_google_gwt_dom_client_Element_$getPropertyString__Lcom_google_gwt_dom_client_Element_2Ljava_lang_String_2Ljava_lang_String_2(this$static.com_geek_afric_client_view_Acceuil_topPanel.com_geek_afric_client_view_TopPanel_recherche.com_google_gwt_user_client_ui_SuggestBox_box.com_google_gwt_user_client_ui_UIObject_element, $intern_92));
  return token;
}

function com_geek_afric_client_view_Acceuil_$setFichiers__Lcom_geek_afric_client_view_Acceuil_2Ljava_util_ArrayList_2V(this$static, files){
  var com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0;
  com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_topLeft);
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_topLeft, (com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0 = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0 = new com_google_gwt_user_client_ui_Label_Label__V , com_google_gwt_user_client_ui_DirectionalTextHelper_$setTextOrHtml__Lcom_google_gwt_user_client_ui_DirectionalTextHelper_2Ljava_lang_String_2ZV(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0.com_google_gwt_user_client_ui_LabelBase_directionalTextHelper, 'Bienvenue dans ton space fichier', false) , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = 'welcome-message' , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185 , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0 = new com_google_gwt_user_client_ui_Label_Label__V , com_google_gwt_user_client_ui_Label_$setText__Lcom_google_gwt_user_client_ui_Label_2Ljava_lang_String_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0, com_geek_afric_shared_User_$getDisplayname__Lcom_geek_afric_shared_User_2Ljava_lang_String_2(this$static.com_geek_afric_client_view_Acceuil_user)) , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = 'style-name' , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185 , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0 = new com_google_gwt_user_client_ui_Button_Button__Ljava_lang_String_2V('Afficher vos fichiers') , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0.com_google_gwt_user_client_ui_UIObject_element.setAttribute($intern_209, 'Cliquer pour voir la liste de vos fichiers') , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0.com_google_gwt_user_client_ui_UIObject_element[$intern_206] = $intern_187 , com_google_gwt_user_client_ui_CellPanel_$setCellVerticalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasVerticalAlignment$VerticalAlignmentConstant_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0, (com_google_gwt_user_client_ui_HasVerticalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasVerticalAlignment_ALIGN_1BOTTOM)) , com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_welcome_0) , com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0) , com_google_gwt_user_client_ui_CellPanel_$setCellHorizontalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_userName_0, (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER)) , com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0) , com_google_gwt_user_client_ui_CellPanel_$setCellHorizontalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0, com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0, com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1RIGHT) , com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_showFiles_0, new com_geek_afric_client_view_Acceuil$2_Acceuil$2__Lcom_geek_afric_client_view_Acceuil_2V(this$static), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE)) , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0.com_google_gwt_user_client_ui_UIObject_element.style[$intern_178] = $intern_185 , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0.com_google_gwt_user_client_ui_UIObject_element.style[$intern_180] = $intern_185 , com_geek_afric_client_view_Acceuil_$createTopLeft__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2_panel_0));
  if (!files || files.java_util_ArrayList_size == 0) {
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_topRight);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_topRight, com_geek_afric_client_view_Acceuil_$createEmptyFile__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2(this$static));
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, false);
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomRight, false);
    return;
  }
  if (files.java_util_ArrayList_size == 1) {
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_topRight);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_topRight, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(0, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[0]), Q$com_geek_afric_shared_Fichier)));
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_topRight, true);
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, com_geek_afric_client_view_Acceuil_$createEmptyFile__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2(this$static));
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, true);
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomRight, false);
  }
   else if (files.java_util_ArrayList_size == 2) {
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_topRight);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_topRight, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(0, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[0]), Q$com_geek_afric_shared_Fichier)));
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(1, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[1]), Q$com_geek_afric_shared_Fichier)));
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_bottomRight);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_bottomRight, com_geek_afric_client_view_Acceuil_$createEmptyFile__Lcom_geek_afric_client_view_Acceuil_2Lcom_google_gwt_user_client_ui_Widget_2(this$static));
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, true);
    com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_bottomRight, true);
  }
   else if (files.java_util_ArrayList_size >= 3) {
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_topRight);
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft);
    com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.com_geek_afric_client_view_Acceuil_bottomRight);
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_topRight, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(0, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[0]), Q$com_geek_afric_shared_Fichier)));
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_bottomLeft, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(1, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[1]), Q$com_geek_afric_shared_Fichier)));
    com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.com_geek_afric_client_view_Acceuil_bottomRight, com_geek_afric_client_view_Acceuil_$createFichier__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_shared_Fichier_2Lcom_google_gwt_user_client_ui_Widget_2(this$static, com_google_gwt_lang_Cast_dynamicCast__Ljava_lang_Object_2ILjava_lang_Object_2((java_util_AbstractList_checkIndex__IIV(2, files.java_util_ArrayList_size) , files.java_util_ArrayList_array[2]), Q$com_geek_afric_shared_Fichier)));
  }
}

function com_geek_afric_client_view_Acceuil_$setListener__Lcom_geek_afric_client_view_Acceuil_2Lcom_geek_afric_client_view_Acceuil$Listener_2V(this$static, listener){
  this$static.com_geek_afric_client_view_Acceuil_listener = listener;
  com_geek_afric_client_view_TopPanel_$setListener__Lcom_geek_afric_client_view_TopPanel_2Lcom_geek_afric_client_view_TopPanel$Listener_2V(this$static.com_geek_afric_client_view_Acceuil_topPanel, new com_geek_afric_client_view_Acceuil$6_Acceuil$6__Lcom_geek_afric_client_view_Acceuil_2V(listener));
}

function com_geek_afric_client_view_Acceuil_$setLoader__Lcom_geek_afric_client_view_Acceuil_2ZV(this$static, load){
  com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_loader, load);
  com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this$static.com_geek_afric_client_view_Acceuil_flexTable, !load);
}

function com_geek_afric_client_view_Acceuil_$setMailCount__Lcom_geek_afric_client_view_Acceuil_2IV(this$static, count){
  com_google_gwt_user_client_ui_Label_$setText__Lcom_google_gwt_user_client_ui_Label_2Ljava_lang_String_2V(this$static.com_geek_afric_client_view_Acceuil_mails, count > 1?$intern_210 + count + ' non lus)':$intern_210 + count + ' non lu)');
}

function com_geek_afric_client_view_Acceuil_$setTokens__Lcom_geek_afric_client_view_Acceuil_2Ljava_util_Set_2V(this$static, tokens){
  !!this$static.com_geek_afric_client_view_Acceuil_topPanel && com_geek_afric_client_view_TopPanel_$setTokens__Lcom_geek_afric_client_view_TopPanel_2Ljava_util_Set_2V(this$static.com_geek_afric_client_view_Acceuil_topPanel, tokens);
}

function com_geek_afric_client_view_Acceuil_Acceuil__Lcom_geek_afric_shared_User_2V(user){
  this.com_geek_afric_client_view_Acceuil_topPanel = new com_geek_afric_client_view_TopPanel_TopPanel__V;
  this.com_geek_afric_client_view_Acceuil_mails = new com_google_gwt_user_client_ui_Label_Label__V;
  this.com_geek_afric_client_view_Acceuil_leftPanel = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_panel = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_flexTable = new com_google_gwt_user_client_ui_FlexTable_FlexTable__V;
  this.com_geek_afric_client_view_Acceuil_topLeft = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_topRight = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_bottomLeft = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_bottomRight = new com_google_gwt_user_client_ui_VerticalPanel_VerticalPanel__V;
  this.com_geek_afric_client_view_Acceuil_loader = new com_google_gwt_user_client_ui_Image_Image__Lcom_google_gwt_resources_client_ImageResource_2V((com_geek_afric_client_view_Images_1en_1InlineClientBundleGenerator$defaultLoaderInitializer_$clinit__V() , com_geek_afric_client_view_Images_1en_1InlineClientBundleGenerator_defaultLoader));
  this.com_geek_afric_client_view_Acceuil_user = user;
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_panel, this.com_geek_afric_client_view_Acceuil_loader);
  com_google_gwt_user_client_ui_CellPanel_$setCellHorizontalAlignment__Lcom_google_gwt_user_client_ui_CellPanel_2Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_user_client_ui_HasHorizontalAlignment$HorizontalAlignmentConstant_2V(this.com_geek_afric_client_view_Acceuil_panel, this.com_geek_afric_client_view_Acceuil_loader, (com_google_gwt_user_client_ui_HasHorizontalAlignment_$clinit__V() , com_google_gwt_user_client_ui_HasHorizontalAlignment_ALIGN_1CENTER));
  com_google_gwt_user_client_ui_UIObject_$setVisible__Lcom_google_gwt_user_client_ui_UIObject_2ZV(this.com_geek_afric_client_view_Acceuil_loader, false);
  com_google_gwt_user_client_ui_VerticalPanel_$add__Lcom_google_gwt_user_client_ui_VerticalPanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_panel, this.com_geek_afric_client_view_Acceuil_flexTable);
  com_google_gwt_user_client_ui_Composite_$initWidget__Lcom_google_gwt_user_client_ui_Composite_2Lcom_google_gwt_user_client_ui_Widget_2V(this, this.com_geek_afric_client_view_Acceuil_panel);
  com_google_gwt_user_client_ui_UIObject_$setSize__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_flexTable, $intern_162, $intern_211);
  com_google_gwt_user_client_ui_UIObject_$setStyleName__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_topLeft, $intern_212);
  com_google_gwt_user_client_ui_HTMLTable_$setWidget__Lcom_google_gwt_user_client_ui_HTMLTable_2IILcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_flexTable, 0, 0, this.com_geek_afric_client_view_Acceuil_topLeft);
  com_google_gwt_user_client_ui_UIObject_$setSize__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_topLeft, $intern_185, $intern_185);
  com_google_gwt_user_client_ui_UIObject_$setStyleName__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_topRight, $intern_212);
  com_google_gwt_user_client_ui_HTMLTable_$setWidget__Lcom_google_gwt_user_client_ui_HTMLTable_2IILcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_flexTable, 0, 1, this.com_geek_afric_client_view_Acceuil_topRight);
  com_google_gwt_user_client_ui_UIObject_$setSize__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_topRight, $intern_185, $intern_185);
  com_google_gwt_user_client_ui_UIObject_$setStyleName__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_bottomLeft, $intern_212);
  com_google_gwt_user_client_ui_HTMLTable_$setWidget__Lcom_google_gwt_user_client_ui_HTMLTable_2IILcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_flexTable, 1, 0, this.com_geek_afric_client_view_Acceuil_bottomLeft);
  com_google_gwt_user_client_ui_UIObject_$setSize__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_bottomLeft, $intern_185, $intern_185);
  com_google_gwt_user_client_ui_UIObject_$setStyleName__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_bottomRight, $intern_212);
  com_google_gwt_user_client_ui_HTMLTable_$setWidget__Lcom_google_gwt_user_client_ui_HTMLTable_2IILcom_google_gwt_user_client_ui_Widget_2V(this.com_geek_afric_client_view_Acceuil_flexTable, 1, 1, this.com_geek_afric_client_view_Acceuil_bottomRight);
  com_google_gwt_user_client_ui_UIObject_$setSize__Lcom_google_gwt_user_client_ui_UIObject_2Ljava_lang_String_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_bottomRight, $intern_185, $intern_185);
  com_google_gwt_user_client_ui_Label_$setText__Lcom_google_gwt_user_client_ui_Label_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil_mails, 'Mails');
  com_google_gwt_user_client_ui_Widget_$addDomHandler__Lcom_google_gwt_user_client_ui_Widget_2Lcom_google_gwt_event_shared_EventHandler_2Lcom_google_gwt_event_dom_client_DomEvent$Type_2Lcom_google_gwt_event_shared_HandlerRegistration_2(this.com_geek_afric_client_view_Acceuil_mails, new com_geek_afric_client_view_Acceuil$1_Acceuil$1__Lcom_geek_afric_client_view_Acceuil_2V(this), (com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_$clinit__V() , com_google_gwt_event_dom_client_ClickEvent_TYPE));
  com_geek_afric_client_view_TopPanel_$insert__Lcom_geek_afric_client_view_TopPanel_2Lcom_google_gwt_user_client_ui_Widget_2IV(this.com_geek_afric_client_view_Acceuil_topPanel, this.com_geek_afric_client_view_Acceuil_mails);
}

function com_geek_afric_client_view_Acceuil(){
}

_ = com_geek_afric_client_view_Acceuil_Acceuil__Lcom_geek_afric_shared_User_2V.prototype = com_geek_afric_client_view_Acceuil.prototype = new com_google_gwt_user_client_ui_Composite;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil_12_1classLit;
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_logical_shared_HasAttachHandlers, Q$com_google_gwt_event_shared_HasHandlers, Q$com_google_gwt_user_client_EventListener, Q$com_google_gwt_user_client_ui_HasVisibility, Q$com_google_gwt_user_client_ui_IsRenderable, Q$com_google_gwt_user_client_ui_IsWidget, Q$com_google_gwt_user_client_ui_UIObject, Q$com_google_gwt_user_client_ui_Widget]);
_.com_geek_afric_client_view_Acceuil_listener = null;
_.com_geek_afric_client_view_Acceuil_user = null;
function com_geek_afric_client_view_Acceuil$1_Acceuil$1__Lcom_geek_afric_client_view_Acceuil_2V(this$0){
  this.com_geek_afric_client_view_Acceuil$1_this$0 = this$0;
}

function com_geek_afric_client_view_Acceuil$1(){
}

_ = com_geek_afric_client_view_Acceuil$1_Acceuil$1__Lcom_geek_afric_client_view_Acceuil_2V.prototype = com_geek_afric_client_view_Acceuil$1.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil$1_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$1_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function com_geek_afric_client_view_Acceuil$1_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_view_Acceuil$1_this$0.com_geek_afric_client_view_Acceuil_listener.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_MailEvent_MailEvent__Lcom_geek_afric_shared_User_2ILjava_lang_String_2V);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.com_geek_afric_client_view_Acceuil$1_this$0 = null;
function com_geek_afric_client_view_Acceuil$2_Acceuil$2__Lcom_geek_afric_client_view_Acceuil_2V(this$0){
  this.com_geek_afric_client_view_Acceuil$2_this$0 = this$0;
}

function com_geek_afric_client_view_Acceuil$2(){
}

_ = com_geek_afric_client_view_Acceuil$2_Acceuil$2__Lcom_geek_afric_client_view_Acceuil_2V.prototype = com_geek_afric_client_view_Acceuil$2.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil$2_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$2_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function com_geek_afric_client_view_Acceuil$2_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickShowFiles__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil$2_this$0.com_geek_afric_client_view_Acceuil_listener, this.com_geek_afric_client_view_Acceuil$2_this$0.com_geek_afric_client_view_Acceuil_user);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.com_geek_afric_client_view_Acceuil$2_this$0 = null;
function com_geek_afric_client_view_Acceuil$3_Acceuil$3__Lcom_geek_afric_client_view_Acceuil_2V(this$0, val$file){
  this.com_geek_afric_client_view_Acceuil$3_this$0 = this$0;
  this.com_geek_afric_client_view_Acceuil$3_val$file = val$file;
}

function com_geek_afric_client_view_Acceuil$3(){
}

_ = com_geek_afric_client_view_Acceuil$3_Acceuil$3__Lcom_geek_afric_client_view_Acceuil_2V.prototype = com_geek_afric_client_view_Acceuil$3.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil$3_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$3_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function com_geek_afric_client_view_Acceuil$3_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickTitle__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Lcom_geek_afric_shared_Fichier_2V(this.com_geek_afric_client_view_Acceuil$3_this$0.com_geek_afric_client_view_Acceuil_listener, this.com_geek_afric_client_view_Acceuil$3_val$file);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.com_geek_afric_client_view_Acceuil$3_this$0 = null;
_.com_geek_afric_client_view_Acceuil$3_val$file = null;
function com_geek_afric_client_view_Acceuil$5_Acceuil$5__Lcom_geek_afric_client_view_Acceuil_2V(this$0){
  this.com_geek_afric_client_view_Acceuil$5_this$0 = this$0;
}

function com_geek_afric_client_view_Acceuil$5(){
}

_ = com_geek_afric_client_view_Acceuil$5_Acceuil$5__Lcom_geek_afric_client_view_Acceuil_2V.prototype = com_geek_afric_client_view_Acceuil$5.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil$5_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$5_12_1classLit;
}
;
_.onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V = function com_geek_afric_client_view_Acceuil$5_onClick__Lcom_google_gwt_event_dom_client_ClickEvent_2V(event){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickTitle__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Lcom_geek_afric_shared_Fichier_2V(this.com_geek_afric_client_view_Acceuil$5_this$0.com_geek_afric_client_view_Acceuil_listener, null);
}
;
_.java_lang_Object_castableTypeMap$ = makeCastMap([Q$com_google_gwt_event_dom_client_ClickHandler, Q$com_google_gwt_event_shared_EventHandler]);
_.com_geek_afric_client_view_Acceuil$5_this$0 = null;
function com_geek_afric_client_view_Acceuil$6_Acceuil$6__Lcom_geek_afric_client_view_Acceuil_2V(val$listener){
  this.com_geek_afric_client_view_Acceuil$6_val$listener = val$listener;
}

function com_geek_afric_client_view_Acceuil$6(){
}

_ = com_geek_afric_client_view_Acceuil$6_Acceuil$6__Lcom_geek_afric_client_view_Acceuil_2V.prototype = com_geek_afric_client_view_Acceuil$6.prototype = new java_lang_Object;
_.getClass__Ljava_lang_Class_2$ = function com_geek_afric_client_view_Acceuil$6_getClass__Ljava_lang_Class_2(){
  return com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$6_12_1classLit;
}
;
_.getRechercheSelectHandler__Lcom_google_gwt_event_logical_shared_SelectionHandler_2 = function com_geek_afric_client_view_Acceuil$6_getRechercheSelectHandler__Lcom_google_gwt_event_logical_shared_SelectionHandler_2(){
  return com_geek_afric_client_presenter_AcceuilPresenter$1_$getRechercheSelectHandler__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Lcom_google_gwt_event_logical_shared_SelectionHandler_2(this.com_geek_afric_client_view_Acceuil$6_val$listener);
}
;
_.onClickAcceuil__V = function com_geek_afric_client_view_Acceuil$6_onClickAcceuil__V(){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_view_Acceuil$6_val$listener.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_AcceuilEvent_AcceuilEvent__V);
}
;
_.onClickDeconnexion__V = function com_geek_afric_client_view_Acceuil$6_onClickDeconnexion__V(){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickDeconnexion__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this.com_geek_afric_client_view_Acceuil$6_val$listener);
}
;
_.onClickFichiers__V = function com_geek_afric_client_view_Acceuil$6_onClickFichiers__V(){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickFichiers__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2V(this.com_geek_afric_client_view_Acceuil$6_val$listener);
}
;
_.onClickPartages__V = function com_geek_afric_client_view_Acceuil$6_onClickPartages__V(){
  com_google_gwt_event_shared_HandlerManager_$fireEvent__Lcom_google_gwt_event_shared_HandlerManager_2Lcom_google_gwt_event_shared_GwtEvent_2V(this.com_geek_afric_client_view_Acceuil$6_val$listener.com_geek_afric_client_presenter_AcceuilPresenter$1_this$0.com_geek_afric_client_presenter_AcceuilPresenter_eventBus, new com_geek_afric_client_event_FichierListEvent_FichierListEvent__Ljava_lang_String_2IV($intern_200, 0));
}
;
_.onClickSearch__Ljava_lang_String_2V = function com_geek_afric_client_view_Acceuil$6_onClickSearch__Ljava_lang_String_2V(token){
  com_geek_afric_client_presenter_AcceuilPresenter$1_$onClickSearch__Lcom_geek_afric_client_presenter_AcceuilPresenter$1_2Ljava_lang_String_2V(this.com_geek_afric_client_view_Acceuil$6_val$listener, token);
}
;
_.com_geek_afric_client_view_Acceuil$6_val$listener = null;
var com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1event_1MailEvent_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_213, 'MailEvent'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$1'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1$1_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$1$1'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$1$2_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$1$2'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$2_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$2'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$3_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$3'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1presenter_1AcceuilPresenter$4_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_195, 'AcceuilPresenter$4'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, $intern_214), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$1_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, 'Acceuil$1'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$2_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, 'Acceuil$2'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$3_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, 'Acceuil$3'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$5_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, 'Acceuil$5'), com_google_gwt_lang_ClassLiteralHolder_Lcom_1geek_1afric_1client_1view_1Acceuil$6_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_196, 'Acceuil$6');
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(2);
